### ISSUE TITLE
2D Projection visualisation - color color diagram

### ISSUE THREAD

**Issue by MaxRonce** [astroinfo-hacks/2023-sfh-galaxy-classification#2]

**Comment by aboucaud** [comment]
Hi @MaxRonce could you put some plots in here ?

**Comment by MaxRonce** [comment]
The 2D projection visualisation was done in the PCA branch
And we'll try do add some C/C diagram and physc/cluster corelation diagram

**Comment by MaxRonce** [comment]
The 2D projection visualisation was done in the PCA branch
And we'll try do add some C/C diagram and physc/cluster corelation diagram
